// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewConcentrate struct {
	Name     string `json:"name"`
	VendorID string `json:"vendorId"`
}

type NewConcentrateURL struct {
	ConcentrateID string `json:"concentrateId"`
	Description   string `json:"description"`
	URL           string `json:"url"`
}

type NewVendor struct {
	Name string `json:"name"`
	Code string `json:"code"`
}

type NewVendorURL struct {
	VendorID    string `json:"vendorId"`
	Description string `json:"description"`
	URL         string `json:"url"`
}

type URL struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	URL         string `json:"url"`
}
